spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:initSurveyResultType.sql, classpath:initQuestion.sql, classpath:initOption.sql
      mode: always

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

server:
  tomcat:
    accesslog:
      enabled: true
      directory: logs
      suffix: .log
      prefix: access_log
      file-date-format: .yyyy-MM-dd
      pattern: '%h %u %t "%r" %s %b "%{Referer}i" "%{User-Agent}i" %q'
    basedir: .
