spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/neipclova
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
