spring:
  application:
    name: neipclova
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:initSurveyResultType.sql, classpath:initQuestion.sql, classpath:initOption.sql
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  metrics:
    tags:
      application: ${spring.application.name}

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
