INSERT INTO public.result_type(result_type, surveytype_id) VALUES ('TRIP', 1);
INSERT INTO public.result_type(result_type, surveytype_id) VALUES ('BAND', 1);
INSERT INTO public.result_type(result_type, surveytype_id) VALUES ('DANCE', 1);
INSERT INTO public.result_type(result_type, surveytype_id) VALUES ('CLIMBING', 1);
INSERT INTO public.result_type(result_type, surveytype_id) VALUES ('READING', 1);
INSERT INTO public.result_type(result_type, surveytype_id) VALUES ('STOCK_INVESTMENT', 1);
INSERT INTO public.result_type(result_type, surveytype_id) VALUES ('DEBATE', 1);
INSERT INTO public.result_type(result_type, surveytype_id) VALUES ('CALLIGRAPHY', 1);
INSERT INTO public.result_type(result_type, surveytype_id) VALUES ('STAY_HYDRATED', 1);