version: "3.8"
services:
  db:
    volumes:
      - ./postgreData:/var/lib/postgresql/data
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  prometheus:
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: prometheus_container
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
  grafana:
    container_name: grafana_container
    image: grafana/grafana
    depends_on:
      - prometheus
    restart: always
    ports:
      - "3001:3000"
